services:
  # Network A: Ground Segment
  ground-node-a:
    build:
      context: .
      dockerfile: docker/ground_node/Dockerfile
    container_name: ground-node-a
    networks:
      - ground-net
    stdin_open: true
    tty: true

  malicious-node:
    build:
      context: .
      dockerfile: docker/malicious_node/Dockerfile
    container_name: malicious-node
    depends_on:
      - ground-node-a
    networks:
      - ground-net
    stdin_open: true
    tty: true

  # The Bridge: CSP Firewall
  firewall:
    build:
      context: ./docker/firewall
      dockerfile: Dockerfile
    container_name: firewall
    environment:
      - HUB_A_IP=ground-node-a
      - HUB_B_IP=sat-node-b
    depends_on:
      - ground-node-a
      - sat-node-b
    networks:
      - ground-net
      - sat-net

  # Network B: Space Segment
  sat-node-b:
    build:
      context: .
      dockerfile: docker/sat_node/Dockerfile
    container_name: sat-node-b
    networks:
      - sat-net
    stdin_open: true
    tty: true

networks:
  ground-net:
    driver: bridge
  sat-net:
    driver: bridge
